# Generated by Django 4.2.6 on 2023-12-24 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenIntegral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.BooleanField(choices=[(True, ''), (True, ''), (True, ''), (False, '')])),
            ],
        ),
        migrations.CreateModel(
            name='LivePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Отсутствует', 'Отсутствует'), ('Кампус', 'Кампус'), ('Город', 'Город'), ('Подвал', 'Подвал'), ('Под мостом', 'Под мостом')], max_length=20, verbose_name='Предпочитаемое место жительства')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_math', models.BooleanField(verbose_name='Математик?')),
                ('chosen_integral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.chosenintegral')),
                ('live_place', models.ManyToManyField(to='register.liveplace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
