# Generated by Django 4.2.6 on 2023-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenintegral',
            name='integral',
            field=models.BooleanField(choices=[(True, '1'), (True, '2'), (True, '3'), (False, '4')]),
        ),
    ]
