# Generated by Django 4.2.6 on 2023-12-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_chosenintegral_integral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='chosen_integral',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='chosen_integrals',
            field=models.ManyToManyField(to='register.chosenintegral'),
        ),
        migrations.AlterField(
            model_name='chosenintegral',
            name='integral',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Выбранные интегралы'),
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='live_place',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='live_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.liveplace'),
            preserve_default=False,
        ),
    ]
